# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Allow longer lines in code blocks
  code_blocks: true
  # Allow longer lines in tables
  tables: true

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML elements
  allowed_elements:
    - br
    - img
    - div
    - span

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2

# MD029/ol-prefix - Ordered list item prefix
MD029:
  # List style
  style: "one_or_ordered"
