repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    -   id: markdownlint
        args: [--config=.markdownlint.yaml]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm  # GitHub-Flavored Markdown
        -   mdformat-frontmatter  # YAML frontmatter
        -   mdformat-footnote  # Footnotes

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: v0.1.0
    hooks:
    -   id: uv-sync
        name: Sync dependencies with uv
        args: [--python-version=3.8, --extras=dev,docs]
