repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    -   id: markdownlint
        args: [--config=.markdownlint.yaml]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm  # GitHub-Flavored Markdown
        -   mdformat-frontmatter  # YAML frontmatter
        -   mdformat-footnote  # Footnotes
