# Site settings for Pragmatic Python book
title: Pragmatic Python
description: A pragmatic guide to Python programming
author: Prayson Wilfred Daniel
remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
permalink: pretty

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/proteusiq/pragmatic-python

# Development settings
development:
  markdown_linting: true
  pre_commit_hooks: true
  package_manager: uv
  dependency_management: pyproject.toml
