[project]
name = "pragmatic-python"
version = "0.1.0"
description = "Pragmatic Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ghp-import>=2.1.0",
    "jupyter-book>=2.0.0a0",
    "sphinx-inline-tabs>=2023.4.21",
]
